### ISSUE TITLE
Bootstrap basic site and setup router

### ISSUE THREAD

**Issue by pdvorchik** [townhallproject/admin#1]
Before we begin this issue we need to select a tech stack and a template.

I believe most of the team is comfortable with react so I'm happy to go with that (it's not my strong suit, but this is a good chance to learn).

As far as templates go, I strongly suggest https://coreui.io/react/ but am definitely open to other options.  @meganrm @Alan-mag (don't know Raegan's username so can't highlight her) are there other templates you'd like to use, or is everyone good with coreui?

We should also probably canonize how we want to handle [side-effects](https://goshakkk.name/redux-side-effect-approaches/), and if there's any other tooling that would be useful.  Personally I'm in love with RxJs so I'm going to suggest we go with https://redux-observable.js.org/ but I'm open to other ideas.

**Comment by meganrm** [comment]
CoreUI seems good...i've used ant.d and material UI pretty extensively. AntD is my favorite, but it doesnt have graphs or the layout that coreUI does. 

For side effects I prefer middleware. I've used both thunk and redux-logic. I like redux-logic.... https://github.com/jeffbski/redux-logic

**Comment by Alan-mag** [comment]
I also like [antd](https://ant.design/), and I know that Formidable Labs has build React components for data visualization 'done easy' (using d3) [https://github.com/FormidableLabs/victory](url).

Having said that, I don't have experience with coreUI, but it looks pretty nice just glancing at the site. As for side effects, ditto with what Megan said.

**Comment by meganrm** [comment]
Ok cool. I'm mostly on board, but can you point me to the actual react api for core-ui? The examples I've seen seem to still involve writing a lot of html markup...I followed the links to react docs but it goes to a general markup description that looks just like bootstrap.  The other thing I'm not thrilled about is that it is jquery dependent. I think before we really start developing with it it would be helpful to have a branch where you've implemented it so we can take a look

For graphs, I really like plotly.js ' react api... it's built on d3 but with a really great react implementation. But if there is any plotting we decide to do that goes beyond what they cover it would be great to have you implement that in d3 directly. 

For organization, this is the template we worked out at work, https://github.com/meganrm/base-react-redux-app. It has readmes in most of the folders to explain our thinking for what goes in each directory. Let me know what you think, it may be a little overkill, but it's nice for me to have things as similar as possible. (obviously ignoring the typescript and the java). I'm agnostic to the styling scripting choice. This is set up with css modules, but i like less and scss as well. 

For routing... this may be unconventional but I don't really like react router. I'm overhauling the submission form right now and experimenting with sticking with pagejs while adding a build process and state management and it seems to be going well.

**Comment by pdvorchik** [comment]
There's no API: it's just an admin dashboard template, not a framework or module.  It has a a ton of fully styled react components -- mostly based off on https://reactstrap.github.io/ -- specifically targeted at dashboard implementation.  This version is done solely in react, there's no jquery.

It comes with a bunch of useful tooling: fully configured webpack (AOT, JIT), livereload, linting, test harness, sass compilation, etc.

While we could start with a barebones seed and reproduce the various pieces, this gives us a huge jump start.  All the components are fully styled and consistent.  All the tooling works out of the box.  We just slap it together and then implement the store, side effects, and some custom components.

Here's a branch where I've started to do the pages, layout, and routing:  https://github.com/townhallproject/admin/tree/%231-Bootstrap-and-Router

Run dev server (with live reload):
```npm run start```

Production builds:
```npm run build```

Testing:
```npm run test```

Re other tech: I definitely prefer sass over css.  Nested declarations alone make it worth while.  I'm fine with typescript too (love the IDE tooling!), and am happy to use it as long as the rest of the team is comfortable with it.

P.S.  I'm not suggesting we use it for this project, but you guys should definitely check out https://github.com/ReactiveX/rxjs -- it's a complete and utter game-changer when working with the redux store.  It implements observables (think if promises and streams had a baby), smart merging operators, and most common manipulation becomes chainable pure functional operators.  Once you use it you won't want to ever go back to implementing stores without it.
