### ISSUE TITLE
Researchers - Search

### ISSUE THREAD

**Issue by pdvorchik** [townhallproject/admin#12]
**User Story**
An admin wants to be able to search for researchers and get basic info

**URI**
`domain.com/researchers/`

**Questions**
What are the results here, Town Halls or Reseachers?  If they're THs we should probably do a table with a link to a researcher modal.  If they're researchers we can do cards and don't need a modal. 

Should we include "pending" events?

**Sub issues** (need to spin up)
- [ ] Table or card view
- [ ] Redux action, reducers, and side effects to search for Researchers.
- [ ] Maybe some cool graphs
- [ ] Maybe an edit/detail modal

**Other notes**
Info to include: Date a Researcher started, how many weeks/MOCs they've missed, other comprehensive data.

Search/filters: Researcher, MoC, State, Chamber, data select (federal vs each state).

**Wire**
![image](https://user-images.githubusercontent.com/4419203/43809404-ff6cfd78-9a7f-11e8-95fc-0e6e06df1758.png)

**Comment by meganrm** [comment]
updated specs: 
Call this "Research tracking" 
At sortable table with columns:  'Moc/lawmaker, District, assigned Researcher, Last updated, last updated by, last researcher action'
Researcher field should be editable (as a database lookup) to change or remove a researcher assigned to an Moc
A button next to the researcher name that is a `mailto:` link

**Comment by pdvorchik** [comment]
@meganrm Where's the assigned district/MoC info? Is it part of the User objects or the MoC objects?  I'm not seeing it on either in my test db.

Can I get a sample of the expected JSON?
