### ISSUE TITLE
Create new restriction on Event Approvers?

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/admin#55]
I'm interested in expanding the THP team members who can approve event submissions. But I'd like to restrict people from approving their own events. 

Possible that a given user can only approve events by others but not themselves?

**Comment by meganrm** [comment]
yeah it is possible. this is a good idea

**Comment by nathanmwilliams** [comment]
Cool. (Can you except me from this?)

**Comment by nathanmwilliams** [comment]
So, to make this actionable:

-Add Robert to Admin 2.0

-Restrict Robert and Jenita from approving their own submitted events (Robert can approve Jenita's, Jenita can approve Robert's)

**Comment by meganrm** [comment]
Robert should go to http://thp-admin.herokuapp.com/, select 'admin access' but leave the check mark checked that says 'only approve other people's events'. Then you can approve his access. For jenita I'll manually add this modification
