### ISSUE TITLE
make beta submission form mobile friendly

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/admin#57]
Big obstacle to all our new volunteers being able to do their research, and thus a critical bottleneck in us getting events published.

**Comment by meganrm** [comment]
so it has been updated, it's currently working on mobile. Alan has a PR done right now that improves it as well.

**Comment by nathanmwilliams** [comment]
Okay. We just had a Maryland volunteer quit citing the form as the issue. I'll investigate and try to get a sense of what problem they were having.

**Comment by meganrm** [comment]
yeah, it would be great to get the specific issue. Alan's updates are a big improvement too.

**Comment by nathanmwilliams** [comment]
"Thank you Jenita - I'm sorry but I don't think that this is the right volunteer opportunity for me - I just wasted time again, trying to fill out and submit that form -- I entered all ten names and tried to submit with No New Events clicked three times - each time it seemed to fail. "
