### ISSUE TITLE
[SUBMISSION FORM] logo overlap issue on updated Beta form styling

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/admin#59]
![logo error](https://user-images.githubusercontent.com/25805849/59228466-baf7e000-8b8c-11e9-81a3-4a30a2f9cf64.png)

**Comment by Alan-mag** [comment]
thanks for flagging - noticed this and made changes that were just pushed --> if you reload it may be updated already

**Comment by nathanmwilliams** [comment]
Looks great. Thanks!

**Comment by Alan-mag** [comment]
info-btn should be on right-hand side of header
